use_frameworks!

platform :ios, '10.0'

target 'EffectDivision_Example' do
  pod 'EffectDivision', :path => '../'

  target 'EffectDivision_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
